# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Internet\Python\WSRC\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WSRC(object):
    def setupUi(self, WSRC):
        WSRC.setObjectName("WSRC")
        WSRC.resize(1600, 900)
        WSRC.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.Remote_Area = QtWidgets.QScrollArea(WSRC)
        self.Remote_Area.setGeometry(QtCore.QRect(20, 150, 871, 620))
        self.Remote_Area.setWidgetResizable(True)
        self.Remote_Area.setObjectName("Remote_Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 869, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.remote_terminal = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.remote_terminal.setGeometry(QtCore.QRect(0, 0, 869, 619))
        self.remote_terminal.setStyleSheet("color: rgb(0, 255, 127);")
        self.remote_terminal.setPlainText("")
        self.remote_terminal.setObjectName("remote_terminal")
        self.Remote_Area.setWidget(self.scrollAreaWidgetContents)
        self.output_label = QtWidgets.QLabel(WSRC)
        self.output_label.setGeometry(QtCore.QRect(20, 50, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.output_label.setFont(font)
        self.output_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.output_label.setObjectName("output_label")
        self.send_button = QtWidgets.QPushButton(WSRC)
        self.send_button.setGeometry(QtCore.QRect(710, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.send_button.setFont(font)
        self.send_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"")
        self.send_button.setObjectName("send_button")
        self.send_thing = QtWidgets.QLineEdit(WSRC)
        self.send_thing.setGeometry(QtCore.QRect(240, 80, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.send_thing.setFont(font)
        self.send_thing.setStyleSheet("color: rgb(255, 255, 255);")
        self.send_thing.setObjectName("send_thing")
        self.My_Area = QtWidgets.QScrollArea(WSRC)
        self.My_Area.setGeometry(QtCore.QRect(1030, 140, 561, 621))
        self.My_Area.setWidgetResizable(True)
        self.My_Area.setObjectName("My_Area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 559, 619))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.my_terminal = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.my_terminal.setGeometry(QtCore.QRect(0, 0, 558, 619))
        self.my_terminal.setStyleSheet("color: rgb(0, 255, 127);")
        self.my_terminal.setPlainText("")
        self.my_terminal.setObjectName("my_terminal")
        self.My_Area.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(WSRC)
        QtCore.QMetaObject.connectSlotsByName(WSRC)

    def retranslateUi(self, WSRC):
        _translate = QtCore.QCoreApplication.translate
        WSRC.setWindowTitle(_translate("WSRC", "WSRC"))
        self.output_label.setText(_translate("WSRC", "远程终端"))
        self.send_button.setText(_translate("WSRC", "发送"))
